server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: 04-config-server
          uri: https://github.com/joosbeen/microservices-luigi
          search-paths:
          - config-data
