server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: 09-zipkin-sleuth
          uri: https://github.com/joosbeen/microservices-luigi.git
          search-paths: config-data
