server:
  port: 8081
spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: 05-eureka-server
          uri: https://github.com/joosbeen/microservices-luigi
          search-paths:
          - config-data
